### ISSUE TITLE
Soft Costs module needs updating

### ISSUE THREAD

**Issue by pduff-code** [WISDEM/ORBIT#119]
Defaults are fixed values based on Cost of Wind Energy Review from ~2019/2020.

First enhancement may be based on methodology in ORCA.

**Comment by nRiccobo** [comment]
Should we use this as our latest reference, @pduff-code? https://www.nrel.gov/docs/fy24osti/88335.pdf

It looks like turbine capex and 5 soft costs can be updated in `manager.py`. 
Things we should address: 
1. Do we have updated values for project parameters like site auction price or assessment cost? 
2. Do we just default to fixed-bottom? Since soft costs are different for floating, should we put some smarts in there to adjust the cost based on floating or flixed-bottom?
