### ISSUE TITLE
Is It Possible to Develop Custom Phases?

### ISSUE THREAD

**Issue by SoundsSerious** [WISDEM/ORBIT#182]
Thanks for putting this library together, its a huge help developing first pass cost information for offshore energy.

I working no an NSF funded project where we are studying alternative installation practices and in some ways feel boxed in by the API's specific phases trying to adapt them to our towed configuration (which doesn't require the WTIV for example).

I see there are instructions on customizing a phase but is there anything we can do if we want to add a new phase?  

I see this as an important feature for those straying away from consensus design in an effort to explore new ways to reduce costs.

**Comment by SoundsSerious** [comment]
For instance I would like to simulate a VAWT turbine with a towed-install without the WTIV lifting rig.

Is there any way to achieve that with the current system?

My current thinking is that I would need to develop a custom cost model for this?

**Comment by nRiccobo** [comment]
Hi, 

Thanks for reaching out with your question. We're happy that you're digging into ORBIT! 

There is a way to create custom installation phase and have ORBIT read it. Albeit this is on the more advanced side of its uses. Here is how I'd suggest approaching your non-WTIV project. 

It sounds like the installation is more like a floating rather than a fixed bottom project. If you want to make a custom phase, I'd look under phases/install/quayside/moored.py which is an installation process for a semi-submersible platform with the turbine already attached. A group up tugboats or AHTS vessels will tow the completed turbine/platform to the site and not use the WTIV. Then you can use ProjectManager's register_install_phase method, to add your custom phase. 

1. Review MooredSubInstallation(), see what components are relevant to your process. 
2. Create a new file and give it a unique name like, SoundsSeriousCustomTurbineInstall
3. Register the phase with ProjectManager.register_install_phase(SoundsSeriousCustomTurbineInstall)
4. Then setup your project, project=ProjectManager(config_file). Project.run()
5. print(project.actions) and sift through the dataframe frame to find the events/agents that you defined in step 2. 
6. Also, make sure the TurbineInstallation is not included, then the WTIV will not be used and added into the events/actions

For a VAWT versus HAWT. Note that ORBIT focuses on the balance of station which omits the turbine design. It's not until the final LCOE calculation that the turbine capex comes into play. So you can adjust the turbine_capex and update that in your configuration file. ORBIT currently defaults to $1300 per kW. If you have a cost breakdown of your VAWT, then you can just replace that value.

**Comment by SoundsSerious** [comment]
Wow thanks for getting back to me so quickly! The NREL folks are amazing :)

Thanks for laying out how I can achieve these goals! Didn't realize there was a `register_install_phase` function, that i think opens up the door for customization.

I'm closing this issue since it seems there's a solution at hand. Thanks!
