### ISSUE TITLE
Cable files require "name" parameter to match the filename for module outputs to work.

### ISSUE THREAD

**Issue by JakeNunemaker** [WISDEM/ORBIT#30]
![Screen Shot 2020-05-05 at 2 40 47 PM](https://user-images.githubusercontent.com/42254629/81114248-e4c1a000-8ede-11ea-8f3b-41dc8036defa.png)

and 

![Screen Shot 2020-05-05 at 2 42 52 PM](https://user-images.githubusercontent.com/42254629/81114185-c5c30e00-8ede-11ea-96b9-dcba3286a5b1.png)

will result in

![Screen Shot 2020-05-05 at 2 40 55 PM](https://user-images.githubusercontent.com/42254629/81114071-7f6daf00-8ede-11ea-8e17-b128aa524f63.png)

If the cable file is updated to:

![Screen Shot 2020-05-05 at 2 43 02 PM](https://user-images.githubusercontent.com/42254629/81114195-c9569500-8ede-11ea-9324-29ae87098f3e.png)

outputs will work:

![Screen Shot 2020-05-05 at 2 43 13 PM](https://user-images.githubusercontent.com/42254629/81114207-d2476680-8ede-11ea-8985-5b05f78a6afa.png)

**Comment by JakeNunemaker** [comment]
This applied to `ArraySystemDesign` and `ExportSystemDesign `and I'm assuming `CustomArraySystemDesign`.

**Comment by JakeNunemaker** [comment]
Dropping priority as it is avoidable but something we should revise soon.

**Comment by RHammond2** [comment]
This is how I had specifically designed it to be, so it's not technically a bug. I don't entirely remember the logic, but it was likely to ensure that the cables could be propagated consistently between design and install phases without having to pass a all of the cable parameters around.

That said, it's possible that this requirement is no longer necessary as it seems like the `SimpleCable` class just uses the `linear_density` property at this point rather than needing to extract the actual cable data.

**Comment by JakeNunemaker** [comment]
Would it be an easy lift to remove the "name" parameter and the references to it in the cable modules, and just use the filename so the user doesn't need to keep them in line?

**Comment by RHammond2** [comment]
It'd probably be fairly easy, but could take a couple hours just to make sure I update all the necessary areas.
